import * as dotenv from "dotenv"
import { defineConfig } from "drizzl-kit";

dotenv.config({path: ".env/local"})

if(!process.env.DATABASE_URL){
  throw new Error("database url is not set in .env.local");
}

export default defineConfig({
  schema: "./lib/db/schema.ts",
  out: "./drizzle", //output of all SQL queries generated by drizzle behind the scenes
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
  migrations: {
    table: "__drizzle_migration", //keep files and tables with this name when migrating
    schema: "public"
  },
  verbose: true, //debug
  strict: true, //warning prompts
});
